### ISSUE TITLE
Проблема с событием нажатия на пуш

### ISSUE THREAD

**Issue by No1Ks** [mindbox-cloud/flutter-sdk#106]
Здравствуйте. 
Пытаюсь поймать момент нажатия на пуш уведомление, которое высылаю из Mindbox, но вместо этого событие выстреливает в момент получения пуша, а не в момент клика по нему. 

Android + Flutter. Версия пакета 2.10.1

`Mindbox.instance.registerInAppCallback c CustomInAppCallback` обрабатывает событие до нажатия, как и `onPushClickReceived`

Подскажите пожалуйста, как отловить момент нажатия на сам пуш?

**Comment by sergeysozinov** [comment]
Добрый день
`Mindbox.instance.registerInAppCallback` - не относится к мобильным пушам, этот метод нужен для кастомной обработки при клике и закрытии in-App. Подробнее [здесь](https://developers.mindbox.ru/docs/%D0%BC%D0%B5%D1%82%D0%BE%D0%B4%D1%8B-flutter-sdk#registerinappcallbacks-since-280)

`onPushClickReceived` используется для подписки на события клика по push-уведомлениям. Когда пользователь нажимает на уведомление и запускает приложение, срабатывает указанный колбэк
Подробнее о методе [здесь](https://developers.mindbox.ru/docs/%D0%BC%D0%B5%D1%82%D0%BE%D0%B4%D1%8B-flutter-sdk#onpushclickreceived)

Реализацию можете посмотреть в [примере ](https://developers.mindbox.ru/docs/%D0%BC%D0%B5%D1%82%D0%BE%D0%B4%D1%8B-flutter-sdk#onpushclickreceived)

Если я вас не так понял и документация и примеры не отвечают на ваш вопрос, опишите подробнее кейс и пришлите часть кода

**Comment by No1Ks** [comment]
Добрый день.

`Mindbox.instance.onPushClickReceived(_onMessageFromMindboxHandler);`

```
 static dynamic _onMessageFromMindboxHandler(_, String payload) {
    Log.debug('onMessageFromMindbox: $payload');
    .....
  }
```

При нажатии из скрытого\выключенного состояния отрабатывает корректно, но при открытом приложении событие выстреливает в момент получения, а не в момент тапа по уведомлению.

**Comment by No1Ks** [comment]
Обнаружил причину проблемы. У меня триггерился старый подход через пуши FCM просто. 
Ваш SDK работает корректно!
